version: "3.8"
services:
  # web:
  #   build: .
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - .:/code
  #     - logvolume01:/var/log
  #   links:
  #     - redis
  mailcatcher:
    image: "schickling/mailcatcher"
    ports:
      - "1025:1025"
      - "1080:1080"
volumes:
  logvolume01: {}
